
GET http://localhost:3000
######

GET http://localhost:3000/posts
######

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "top beaches in florida",
    "content": "successfully created posts",
    "published": false,
    "rating": 4
    
}
######

GET http://localhost:3000/posts/5
######

# GET http://localhost:3000/posts/latest
# ######

DELETE  http://localhost:3000/posts/1
######

PUT http://localhost:3000/posts/1
Content-Type: application/json

{
    "title": "Edited Title",
    "content": "Edited Content"
}